"""Behave environment hooks for inventory-bdd.

Generated by behave-gen. Add before/after hooks for scenario, feature, and
all run lifecycle events as needed.
"""

from __future__ import annotations


def before_all(context) -> None:
    """Run once before any feature runs."""


def after_all(context) -> None:
    """Run once after all features have run."""


def before_feature(context, feature) -> None:
    """Run before each feature."""


def after_feature(context, feature) -> None:
    """Run after each feature."""


def before_scenario(context, scenario) -> None:
    """Run before each scenario."""


def after_scenario(context, scenario) -> None:
    """Run after each scenario."""
