"""Authentication/session step definitions for inventory-bdd.

Generated by behave-gen. These steps manage a lightweight in-memory session
(token storage) and pair naturally with the HTTP step library. They use only
the standard library so the generated project has no extra runtime
dependencies.
"""

from __future__ import annotations

from typing import Any

from behave import given, then, when


class _Session:
    """Minimal session state: a token and a store of named values."""

    def __init__(self) -> None:
        self.token: str | None = None
        self.store: dict[str, str] = {}

    @property
    def is_authenticated(self) -> bool:
        return self.token is not None


def _session(context: Any) -> _Session:
    sess = getattr(context, "behave_gen_session", None)
    if sess is None:
        sess = _Session()
        context.behave_gen_session = sess
    return sess


@given("I am not authenticated")
def not_authenticated(context: Any) -> None:
    """Reset the session so no token is present."""
    sess = _session(context)
    sess.token = None
    sess.store.clear()


@given('I have a session token "{token}"')
def have_token(context: Any, token: str) -> None:
    """Seed the session with an explicit token."""
    _session(context).token = token


@when('I store the value "{value}" as "{name}"')
def store_value(context: Any, value: str, name: str) -> None:
    """Store an arbitrary value in the session under ``name``."""
    _session(context).store[name] = value


@when('I clear the session')
def clear_session(context: Any) -> None:
    """Clear all session state."""
    sess = _session(context)
    sess.token = None
    sess.store.clear()


@then("I should be authenticated")
def assert_authenticated(context: Any) -> None:
    """Assert a session token is present."""
    sess = _session(context)
    assert sess.is_authenticated, "Expected an authenticated session, but no token is set."


@then("I should not be authenticated")
def assert_not_authenticated(context: Any) -> None:
    """Assert no session token is present."""
    sess = _session(context)
    assert not sess.is_authenticated, "Expected no session, but a token is present."


@then('the session value "{name}" should be "{value}"')
def assert_session_value(context: Any, name: str, value: str) -> None:
    """Assert a previously stored session value equals ``value``."""
    sess = _session(context)
    assert name in sess.store, f"No session value named {name!r}."
    assert sess.store[name] == value, (
        f"Expected {name}={value!r}, got {sess.store[name]!r}."
    )
